const WORDS = [
  { word: "Aesthetic", type: "noun", def: "A vibe, theme, or look that defines your style or identity online.", example: "Her whole IG is giving clean girl aesthetic.", emoji: "🎨" },
  { word: "AF", type: "acronym", def: "As f—, used to intensify or emphasize something strongly.", example: "That outfit is cute AF.", emoji: "💯" },
  { word: "AFK", type: "acronym", def: "Away From Keyboard — not active, not responding, gone.", example: "Sorry for the late reply I was AFK.", emoji: "🚶" },
  { word: "Alpha", type: "noun", def: "Someone acting like a stereotypical alpha male — confident, dominant, and just too much. Usually said ironically.", example: "He told the teacher to be quiet. That's so Alpha.", emoji: "🐺" },
  { word: "Alt Girl", type: "noun", def: "A girl who vibes outside the mainstream with emo, punk, or edgy style.", example: "She's like full alt girl now, chokers, fishnets, the whole vibe.", emoji: "🖤" },
  { word: "And I Oop", type: "phrase", def: "An expression of sudden shock, embarrassment, or an awkward surprise moment.", example: "He liked my 2016 selfie… and I oop.", emoji: "😳" },
  { word: "Ate", type: "verb", def: "Slayed, served, dominated — did something absolutely flawlessly.", example: "She ate and left no crumbs.", emoji: "✨" },
  { word: "ATP", type: "acronym", def: "At This Point — used when you've hit your limit or are summing up your vibe.", example: "ATP I don't even care anymore.", emoji: "😮‍💨" },
  { word: "Aura", type: "noun", def: "The vibe or energy someone radiates. Your whole presence and aesthetic combined.", example: "Her aura is unreal.", emoji: "🌟" },
  { word: "Aura Farming", type: "phrase", def: "Purposely over-curating your vibe for attention, likes, or clout.", example: "He's just aura farming with that fit.", emoji: "🌾" },
  { word: "Based", type: "adjective", def: "Confidently saying or doing what you believe even if it's unpopular. Unapologetically yourself.", example: "Wearing crocs to prom? Based.", emoji: "😎" },
  { word: "BBG", type: "acronym", def: "Baby girl — a playful or ironic way to hype someone up.", example: "Go off BBG you slayed fr.", emoji: "💅" },
  { word: "Bed Rot", type: "verb", def: "Staying in bed for hours doing absolutely nothing out of burnout or extreme chill.", example: "Not me bed rotting for the third day watching rom-coms.", emoji: "🛌" },
  { word: "Bet", type: "phrase", def: "Okay, agreed, confirmed. A casual yes.", example: '"You coming later?" "Bet."', emoji: "🤝" },
  { word: "Beta", type: "noun", def: "A submissive or passive person — the opposite of alpha. Usually used as an insult.", example: "He's acting so beta around her.", emoji: "😬" },
  { word: "Boomer", type: "noun", def: "An out-of-touch person who doesn't understand internet culture. Not necessarily old — it's a state of mind.", example: "That take is pure boomer energy.", emoji: "👴" },
  { word: "Brainrot", type: "noun", def: "When your brain is fully consumed by a hyper-specific meme, fandom, or internet obsession.", example: "I can't stop quoting this stupid meme. Full brainrot.", emoji: "🧠" },
  { word: "Brat", type: "adjective", def: "Living an authentic, carefree, and slightly chaotic lifestyle. Inspired by Charli XCX.", example: "She's fully in her brat era rn.", emoji: "🌿" },
  { word: "Broligarchy", type: "noun", def: "A group of powerful tech bros with outsized influence. A mix of bro and oligarchy.", example: "Elon and Zuck are peak broligarchy.", emoji: "🤵" },
  { word: "Bugging", type: "verb", def: "Acting wild, irrational, or overreacting for no reason.", example: "She bugging if she thinks that's cute.", emoji: "🐛" },
  { word: "Bussin", type: "adjective", def: "Really, really good — usually about food but applies to anything.", example: "This mac and cheese is bussin frfr.", emoji: "😋" },
  { word: "Cancel", type: "verb", def: "To publicly reject or call out someone for bad behavior.", example: "He's cancelled for that take.", emoji: "🚫" },
  { word: "Canon Event", type: "phrase", def: "A moment in life that was meant to happen — it shaped your story even if it hurt.", example: "Getting your heart broken is a canon event, I can't interfere.", emoji: "📖" },
  { word: "Cap", type: "noun", def: "A lie. No cap means no lie, for real.", example: "She said she met Drake. That's cap.", emoji: "🧢" },
  { word: "Caught in 4K", type: "phrase", def: "Exposed doing something dumb or embarrassing with evidence — screenshots or video.", example: "He said he was sick but got caught in 4K at the party.", emoji: "📹" },
  { word: "Caught Lacking", type: "phrase", def: "Exposed or embarrassed while completely unprepared.", example: "He wore slides in the rain and got caught lacking fr.", emoji: "💀" },
  { word: "Chad", type: "noun", def: "A confident, attractive, top-tier guy. Sometimes serious, sometimes satirical.", example: "He brought two Gatorades and said you looked thirsty. Actual Chad behavior.", emoji: "💪" },
  { word: "Chat", type: "noun", def: "Refers to the audience or viewers in a livestream. Also used to address an imaginary audience.", example: "Chat, what do I even do now??", emoji: "💬" },
  { word: "Chopped", type: "adjective", def: "Destroyed, messed up, or edited badly. Sometimes means ugly.", example: "Bro your cut is CHOPPED.", emoji: "✂️" },
  { word: "Cirb", type: "phrase", def: "Chill I'm rage baiting — a quick way to signal you're trolling on purpose.", example: "You look ugly today. Cirb.", emoji: "🎣" },
  { word: "Clanker", type: "noun", def: "A glitchy, broken, or creepy AI or robot. From Star Wars, now used for any robotic fail.", example: "This Tesla clanker just walked into a wall.", emoji: "🤖" },
  { word: "Clapped", type: "adjective", def: "Ugly, wrecked, or defeated badly.", example: "That filter made me look clapped.", emoji: "😩" },
  { word: "Clout", type: "noun", def: "Social influence, fame, or online status. A clout chaser seeks it desperately.", example: "He's just doing that for clout.", emoji: "⭐" },
  { word: "Cook", type: "verb", def: "To absolutely slay or go off — usually in a debate, performance, or creative moment.", example: "She really cooked with that presentation.", emoji: "👨‍🍳" },
  { word: "Cooked", type: "adjective", def: "Messed up, done for, or completely gone. Your situation is hopeless.", example: "I forgot to study. I'm cooked.", emoji: "🔥" },
  { word: "Cracked", type: "adjective", def: "Insanely good at something — especially gaming or sports.", example: "Bro dropped 40 kills in Fortnite, he's cracked.", emoji: "🎮" },
  { word: "Crashing Out", type: "phrase", def: "Completely losing your mind in a public or dramatic way — a full meltdown.", example: "He started throwing his headset on live. Dude's crashing out.", emoji: "😤" },
  { word: "Cringe", type: "adjective", def: "Awkward, embarrassing, or trying too hard.", example: "This skit is pure cringe.", emoji: "😬" },
  { word: "D1", type: "noun", def: "Division 1 — elite, top-tier, built different. The highest stamp of approval.", example: "She's D1 for real.", emoji: "🏆" },
  { word: "Delulu", type: "adjective", def: "Delusional in a funny, confident, or unbothered way. Delulu is the solulu.", example: "She thinks he's texting back. Full delulu.", emoji: "🌀" },
  { word: "Demure", type: "adjective", def: "Mindful, respectful, very cute. Not doing too much at once.", example: "She handled that so demure fr.", emoji: "🩷" },
  { word: "Doomer", type: "noun", def: "A person obsessed with hopelessness, burnout, and pessimism. A meme archetype.", example: "He's been in doomer mode since his stream flopped.", emoji: "😔" },
  { word: "Doom Scroll", type: "verb", def: "Getting stuck scrolling TikTok, Reels, or Shorts for hours and not being able to stop.", example: "It's 3am and I'm still doom scrolling.", emoji: "📱" },
  { word: "E-Boy", type: "noun", def: "A digitally attractive guy with emo, alt, or gamer style who lives online.", example: "He looks like an e-boy who plays Valorant and ghosted you.", emoji: "🎸" },
  { word: "E-Girl", type: "noun", def: "A girl with a strong digital aesthetic — alt fashion, online presence, edgy or cute.", example: "She's giving major e-girl energy.", emoji: "🖤" },
  { word: "Era", type: "noun", def: "A specific phase or mood you're currently living in.", example: "I'm fully in my villain era rn.", emoji: "⏳" },
  { word: "Extra", type: "adjective", def: "Over-the-top, dramatic, or doing the most. Funny or cringe depending on delivery.", example: "He brought sparklers to brunch? So extra.", emoji: "💥" },
  { word: "Face Card", type: "noun", def: "Your face being so attractive it gives you instant clout. The face card never declines.", example: "The outfit is mid but the face card never declines.", emoji: "🪪" },
  { word: "Fam", type: "noun", def: "Bro, dude, homie — casual slang for anyone you're talking to.", example: "Ayo fam, you good?", emoji: "👥" },
  { word: "Fanum Tax", type: "noun", def: "Stealing food off someone else's plate. Named after streamer Fanum.", example: "He hit me with the Fanum Tax on my nuggets.", emoji: "🍟" },
  { word: "Fell Off", type: "phrase", def: "When someone or something lost their hype, relevance, or quality.", example: "He dropped one flop single and everyone said he fell off.", emoji: "📉" },
  { word: "Fein", type: "verb", def: "Desperately wanting something — food, attention, anything. A spin on fiending.", example: "Bro is feining for that Chick-fil-A.", emoji: "😵" },
  { word: "Finna", type: "verb", def: "About to do something. Short for fixing to.", example: "I'm finna log off before I say something wild.", emoji: "⚡" },
  { word: "Fire", type: "adjective", def: "Something extremely good, impressive, or hot in a good way.", example: "That outfit is actually fire omg.", emoji: "🔥" },
  { word: "Fit", type: "noun", def: "Short for outfit. A fit check is showing off what you're wearing.", example: "Fit check before the concert.", emoji: "👗" },
  { word: "Flex", type: "verb", def: "To show off or brag — usually about something material or social.", example: "Not you flexing your AirPods.", emoji: "💪" },
  { word: "Flop", type: "noun", def: "Something or someone that failed, flopped, or is just not giving.", example: "Bro got benched again? He's a flop fr.", emoji: "📉" },
  { word: "FOMO", type: "acronym", def: "Fear of missing out — anxiety over not being included in something fun.", example: "Skipped the party and now I've got FOMO watching everyone's stories.", emoji: "😩" },
  { word: "FR", type: "acronym", def: "For real — used to confirm honesty, seriousness, or agreement.", example: "That food hit different fr.", emoji: "💯" },
  { word: "Fries in the Bag", type: "phrase", def: "Just do it already. Stop stalling and get it done.", example: "Stop talking and just put the fries in the bag.", emoji: "🍟" },
  { word: "Fumble", type: "verb", def: "To mess up a great opportunity — especially in dating or relationships.", example: "He fumbled the bag by texting his ex on their anniversary.", emoji: "🏈" },
  { word: "Gassed Up", type: "phrase", def: "Over-hyped, over-complimented, or getting too big a head from praise.", example: "Don't get gassed up, it was one good game.", emoji: "⛽" },
  { word: "Ghost", type: "verb", def: "To suddenly stop responding to someone with no explanation.", example: "She ghosted me after three weeks. No warning.", emoji: "👻" },
  { word: "Girl Dinner", type: "noun", def: "A chaotic but relatable meal made entirely of random snacks and leftovers.", example: "Crackers, cheese, and a pickle. Girl dinner.", emoji: "🍽️" },
  { word: "Giving", type: "verb", def: "Giving off a certain energy or aesthetic. Often followed by what it's giving.", example: "This outfit is giving main character.", emoji: "✨" },
  { word: "Glaze", type: "verb", def: "To excessively praise or compliment someone to a cringe level.", example: "Stop glazing him, he's not even that good.", emoji: "🍩" },
  { word: "Glow Up", type: "phrase", def: "A major positive transformation in appearance, confidence, or life situation.", example: "Her glow up from freshman year is unreal.", emoji: "✨" },
  { word: "GOAT", type: "acronym", def: "Greatest Of All Time. The undisputed best at something.", example: "Messi is the GOAT no debate.", emoji: "🐐" },
  { word: "Goated", type: "adjective", def: "Being the GOAT or performing at an elite level. Insanely good.", example: "That play was goated fr.", emoji: "🐐" },
  { word: "Gyatt", type: "exclamation", def: "An exclamation of surprise or appreciation — often about someone's appearance.", example: "He walked past and she went gyatt under her breath.", emoji: "👀" },
  { word: "Hits Different", type: "phrase", def: "When something feels more meaningful or intense than usual.", example: "This song hits different at 3am.", emoji: "🎵" },
  { word: "Hyped", type: "adjective", def: "Extremely excited or pumped up about something.", example: "I'm so hyped for this concert.", emoji: "🙌" },
  { word: "Ick", type: "noun", def: "A sudden feeling of disgust or attraction-killer caused by someone's behavior.", example: "He chewed with his mouth open and I got the ick immediately.", emoji: "🤢" },
  { word: "IYKYK", type: "acronym", def: "If You Know You Know — referencing something only a specific group would understand.", example: "That spot on 5th ave IYKYK.", emoji: "🤫" },
  { word: "Lowkey", type: "adverb", def: "Slightly, secretly, or in a subtle way. Used to soften a statement.", example: "I lowkey love that song but won't admit it.", emoji: "🤫" },
  { word: "L", type: "noun", def: "A loss or failure. Taking an L means you lost or got humiliated.", example: "He took a massive L in that argument.", emoji: "😬" },
  { word: "Main Character", type: "phrase", def: "Acting like the protagonist of your own movie — everything revolves around you.", example: "She walked in slow-mo. Full main character energy.", emoji: "🎬" },
  { word: "Mid", type: "adjective", def: "Mediocre, average, nothing special. Not good, not bad — just mid.", example: "The movie was mid. I wouldn't rewatch it.", emoji: "😐" },
  { word: "Mewing", type: "verb", def: "Pressing your tongue to the roof of your mouth to define the jawline.", example: "He's been mewing for six months straight.", emoji: "😶" },
  { word: "Mogging", type: "verb", def: "Outclassing or dominating someone in looks, confidence, or presence.", example: "He walked in and mogged everyone in the room.", emoji: "👑" },
  { word: "No Cap", type: "phrase", def: "For real, not lying. Used to emphasize the truth of what you're saying.", example: "That was the best meal I've ever had, no cap.", emoji: "🧢" },
  { word: "NPC", type: "noun", def: "Someone acting robotic or without personality — like a video game background character.", example: "She just nodded the whole meeting. Total NPC energy.", emoji: "🤖" },
  { word: "Ohio", type: "noun", def: "An imaginary cursed wasteland where weird, absurd, physics-defying things are normal.", example: "That could only happen in Ohio.", emoji: "🗺️" },
  { word: "On God", type: "phrase", def: "I swear to God — used to emphasize something is completely true.", example: "On God that was the funniest thing I've ever seen.", emoji: "🙏" },
  { word: "Opp", type: "noun", def: "Opposition — an enemy, rival, or someone who's against you.", example: "Watch out for your opps.", emoji: "⚔️" },
  { word: "Out of Pocket", type: "phrase", def: "Going too far, crossing a line, or saying something wild and inappropriate.", example: "That joke was out of pocket, he needs to chill.", emoji: "😤" },
  { word: "Passed the Vibe Check", type: "phrase", def: "Someone or something has been approved and deemed acceptable by the group.", example: "New guy passed the vibe check, he's cool.", emoji: "✅" },
  { word: "Posting", type: "verb", def: "Hanging around or standing somewhere, usually doing nothing.", example: "We were just posting outside the mall.", emoji: "📍" },
  { word: "Ratio", type: "verb", def: "When a reply gets more likes than the original post — meaning the reply won.", example: "He got ratioed into oblivion.", emoji: "📊" },
  { word: "Rizz", type: "noun", def: "Natural charm or charisma, especially when attracting someone. The most important social skill.", example: "He walked in and immediately had rizz.", emoji: "🔥" },
  { word: "Salty", type: "adjective", def: "Being bitter, upset, or resentful — usually over something minor.", example: "He's so salty he didn't get picked first.", emoji: "🧂" },
  { word: "Say Less", type: "phrase", def: "I understand, no need to explain further. Like bet but even more minimal.", example: '"Ill bring the food." "Say less."', emoji: "🤐" },
  { word: "Shook", type: "adjective", def: "Shocked, surprised, or rattled by something unexpected.", example: "I'm absolutely shook by that plot twist.", emoji: "😲" },
  { word: "Sigma", type: "noun", def: "A lone wolf who operates on their own terms with no need for validation.", example: "He didn't even respond to the groupchat. Sigma move.", emoji: "🐺" },
  { word: "Simp", type: "noun", def: "Someone who does way too much for someone who doesn't reciprocate.", example: "He drove four hours just to see her. He's simping hard.", emoji: "🥺" },
  { word: "Skibidi", type: "adjective", def: "A nonsense filler word that can mean cool, bad, or just chaotic. From Skibidi Toilet.", example: "That was so skibidi of him.", emoji: "🚽" },
  { word: "Skibidi Toilet", type: "noun", def: "A wildly popular absurd animated series about singing toilets fighting cameramen. Origin of much brainrot.", example: "My little cousin watches Skibidi Toilet 24/7.", emoji: "📺" },
  { word: "Slay", type: "verb", def: "To do something impressively well. To absolutely kill it.", example: "She slayed that presentation no notes.", emoji: "💅" },
  { word: "Slept On", type: "phrase", def: "Underrated or overlooked. Not getting the recognition deserved.", example: "That album is so slept on, it's actually incredible.", emoji: "😴" },
  { word: "Sneaky Link", type: "noun", def: "Someone you're secretly seeing or meeting up with — kept off social media.", example: "Nobody knows about his sneaky link.", emoji: "🤫" },
  { word: "Stan", type: "verb", def: "To be an obsessive, dedicated fan of someone or something.", example: "I stan her so hard, she can do no wrong.", emoji: "⭐" },
  { word: "Sybau", type: "phrase", def: "Shut your b— a— up. A blunt way to tell someone to be quiet.", example: "He would not stop talking so she just said sybau.", emoji: "🤫" },
  { word: "Tea", type: "noun", def: "Gossip, drama, or juicy information. Spilling the tea means sharing the gossip.", example: "Spill the tea, what happened at the party?", emoji: "🍵" },
  { word: "Understood the Assignment", type: "phrase", def: "Someone did exactly what was needed and executed perfectly.", example: "She showed up in full costume. Understood the assignment.", emoji: "✅" },
  { word: "Vibe Check", type: "noun", def: "An assessment of someone's energy or mood to see if they fit the situation.", example: "New guy failed the vibe check immediately.", emoji: "✔️" },
  { word: "W", type: "noun", def: "A win. Taking a W means you succeeded or something good happened.", example: "Got the job. That's a massive W.", emoji: "🏆" },
  { word: "Vibe", type: "noun", def: "The overall feeling or energy of a place, person, or situation.", example: "This place has such a good vibe.", emoji: "🌊" },
  { word: "Wig", type: "exclamation", def: "An expression of being so shook your wish flies off. Means wow or mind-blown.", example: "That performance sent my wig to space.", emoji: "💇" },
  { word: "Winter Arc", type: "noun", def: "A self-improvement period during winter — grinding, isolating, and leveling up.", example: "I'm entering my winter arc. No distractions.", emoji: "❄️" },
  { word: "Womp Womp", type: "phrase", def: "A sound used to mock someone complaining or failing at something.", example: "He failed the test and everyone said womp womp.", emoji: "😔" },
  { word: "Yap", type: "verb", def: "To talk excessively, especially about nothing important.", example: "He has been yapping for 20 minutes straight.", emoji: "🗣️" },
  { word: "Zesty", type: "adjective", def: "Extra, flamboyant, or overly enthusiastic in a way that's noticeable.", example: "The way he skipped into the room was a little zesty.", emoji: "🍋" }
];